### ISSUE TITLE
Mod not working on wynncraft

### ISSUE THREAD

**Issue by isaiahvh7** [elijahjibben/Wynncraft-Dynamic-Weather#1]
READ COMMENT BELOW
I don't know why, but no rain is rendering when I run /wynnweather rain. The sky turns dark, but no rain renders, nor does the sound/splash effects. This ONLY happens when i play wynncraft; I tried on some other servers and the rain works on them. I did some testing and this is not because of any other mod I have installed. I tested with particle rain as well, and that also did not work. Pls tell me if you have any ideas why you think this might be happening.

**Comment by isaiahvh7** [comment]
I found out how to fix it. Everyone that wants to use this mod should download [https://www.curseforge.com/minecraft/mc-mods/barriers-dont-block-rain](url), as wynncraft has some kind of barrier ceiling that otherwise blocks rain and weather effects. Please add this to the dependencies section of the page.

**Comment by elijahjibben** [comment]
Thanks for pointing this out, that mod should be in the dependencies and I completely forgot about that.
