### ISSUE TITLE
A tiny incopatible problem.

### ISSUE THREAD

**Issue by NEKECKS** [elijahjibben/Wynncraft-Dynamic-Weather#3]
[2024-08-18-7.log.gz](https://github.com/user-attachments/files/16651561/2024-08-18-7.log.gz)
[copied_log.txt](https://github.com/user-attachments/files/16651568/copied_log.txt)

I made a small mod assembly for myself with the participation of this mod, and the problem is that the game gives an error when loading the world.
After checking the logs, I did not understand anything and went with these logs to the Internet.
I tried to at least find out the problem with the help of "Gemini - by Google" and the chat bot pointed out to me that this mod may be incompatible with some mods.
If anything, I do not require a line fix for this problem, this is already your business, but I think this problem should be taken into account for further correction. (the text is translated into Google Translate, just so that later there are no questions about my crooked English)

**Comment by elijahjibben** [comment]
Hey, it looks like the issue isn't related to Wynncraft Dynamic Weather. It looks like your missing some dependencies listed at the top of the crash report, "modmenu-badges-lib", and "yacl". If its not that it is likely another incompatibility, my mod isn't very invasive so it shouldn't have any issues. Another note- I would recommend not using my mod if your not planning on using the modpack exclusively for the Wynncraft server. It has a lot of features that will act very weird when not on that server, consider a mod like Weather Changer for other applications.
