### ISSUE TITLE
can't create or enter singleplayer worlds

### ISSUE THREAD

**Issue by gmpby** [elijahjibben/Wynncraft-Dynamic-Weather#4]
there's a bug making it so that creating a new world freezes the game indefinitely on the first loading. even creating a new world without the mod installed and trying to access it again with the mod installed crashes the game. mod still works fine and functions as intended in the actual wynncraft server but single-player is not an option with this mod installed.

**Comment by elijahjibben** [comment]
Thank you for your bug report! Never noticed this since my testing was exclusively on server. Bug has been fixed and will be released in the next update release 👍
