### ISSUE TITLE
Incompatibility with singleplayer worlds

### ISSUE THREAD

**Issue by Eduffm14** [elijahjibben/Wynncraft-Dynamic-Weather#6]
Whenever a singleplayer world is loaded, there is a chance the game either crashes or it shows as "Server Closed", and every time you leave a singleplayer world the game crashes

**Comment by elijahjibben** [comment]
Thanks for the bug report, sorry about the delay in fixing this. I actually fixed the bug in the code a month ago and forgot to push a release from being busy. Update is now live on Modrinth or GitHub releases.
